# Generated by Django 2.0.5 on 2018-10-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'About_us',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HomePage Slider', 'HomePage Slider'), ('News Slider', 'News Slider'), ('Collection Slider', 'Collection Slider'), ('Post Slider', 'Post Slider'), ('News Card', 'News Card'), ('Collection Card', 'Collection Card')], max_length=500, unique=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Image_types',
            },
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField(max_length=5)),
                ('longitude', models.FloatField(max_length=5)),
                ('email_address', models.EmailField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Contact_us',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=50000)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('lvl', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Footer')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('lvl', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Main_categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('lvl', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation_bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('parent', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=50000)),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'News_categories',
            },
        ),
        migrations.CreateModel(
            name='News_category_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.News_category')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.New')),
            ],
        ),
        migrations.CreateModel(
            name='Other_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50000)),
                ('post_category', models.CharField(max_length=500)),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Post_categories',
            },
        ),
        migrations.CreateModel(
            name='Post_category_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helping_parameter', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('post_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Post_category')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Social_network_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Social_network_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Social_network_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Social_network_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('tocken_reset_password', models.CharField(max_length=50)),
                ('tocken_reset_password_exp', models.DateField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_type_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.IntegerField(default=0)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Permission')),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.User_type')),
            ],
        ),
        migrations.CreateModel(
            name='Value_proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=50000)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='رسانه',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('فایل', models.FileField(help_text='عکس را در اینجا بارگذاری کنید', upload_to='Media/')),
                ('توضیح', models.CharField(max_length=500)),
                ('عنوان', models.CharField(max_length=500)),
                ('جایگزین', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'رسانه',
            },
        ),
        migrations.AddField(
            model_name='value_proposition',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.User_type'),
        ),
        migrations.AddField(
            model_name='social_network_post',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Social_network_type'),
        ),
        migrations.AddField(
            model_name='social_network_new',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Social_network_type'),
        ),
        migrations.AddField(
            model_name='social_network_content',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Social_network_type'),
        ),
        migrations.AddField(
            model_name='post_category',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='other_program',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='news_category',
            name='media_id',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='new',
            name='card',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncard', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='new',
            name='media_id',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nmedia', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='new',
            name='news_category',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesineapp.News_category'),
        ),
        migrations.AddField(
            model_name='new',
            name='slider',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nslider', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='main_category',
            name='card',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccard', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='main_category',
            name='media_id',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmedia', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='main_category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Main_category'),
        ),
        migrations.AddField(
            model_name='main_category',
            name='slider',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cslider', to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='logo',
            name='logo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='logo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='content',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Banner_type'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='social_network_contetnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.Social_network_content'),
        ),
    ]
