# Generated by Django 2.0.5 on 2018-10-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='بنر',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('عنوان', models.CharField(max_length=500)),
                ('زیرنویس', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_بنر', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'بنر_ها',
            },
        ),
        migrations.CreateModel(
            name='تماس_با_ما',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('آدرس', models.CharField(max_length=500)),
                ('ایمیل', models.CharField(max_length=500)),
                ('تلفن', models.CharField(max_length=500)),
                ('طول_جغرافیایی', models.FloatField()),
                ('عرض_جغرافیایی', models.FloatField()),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'تماس_با_ما',
            },
        ),
        migrations.CreateModel(
            name='خبر',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('عنوان_خبر', models.CharField(max_length=500)),
                ('شرح_خبر', models.TextField()),
                ('متن_مارکتینگ', models.CharField(max_length=500)),
                ('پارامتر_کمکی', models.CharField(blank=True, max_length=500, null=True)),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_رسانه', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nmedia', to='mesineapp.رسانه')),
                ('عکس_مارکتینگ', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nmarketing', to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'خبرها',
            },
        ),
        migrations.CreateModel(
            name='درباره_ما',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('متن', models.TextField()),
                ('حذف', models.IntegerField(default=0)),
                ('عکس۱', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ax1', to='mesineapp.رسانه')),
                ('عکس۲', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ax2', to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'درباره_ما',
            },
        ),
        migrations.CreateModel(
            name='سربرگ',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('متن', models.CharField(max_length=500)),
                ('لینک', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'سربرگ',
            },
        ),
        migrations.CreateModel(
            name='سرویس',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('عنوان', models.CharField(max_length=500)),
                ('زیرنویس', models.CharField(max_length=500)),
                ('پارامتر_کمکی', models.CharField(blank=True, max_length=500, null=True)),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_رسانه', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmedia', to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'سرویس_ها',
            },
        ),
        migrations.CreateModel(
            name='لوگو',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('متن', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_لوگو', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'لوگو',
            },
        ),
        migrations.CreateModel(
            name='منوی_غذا',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('عنوان', models.CharField(max_length=500)),
                ('محتویات', models.CharField(max_length=500)),
                ('متن', models.TextField()),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_رسانه', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'منوی_غذا',
            },
        ),
        migrations.CreateModel(
            name='منوی_محبوب_رستوران',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('عنوان_غذا', models.CharField(max_length=500)),
                ('توضیح', models.CharField(max_length=50000)),
                ('حذف', models.IntegerField(default=0)),
                ('شناسه_رسانه', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'منوی_محبوب_رستوران',
            },
        ),
        migrations.CreateModel(
            name='نوع_شبکه_اجتماعی',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('متن', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'نوع_شبکه_اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='نوع_عکس',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('نوع', models.CharField(choices=[('صفحه اصلی', 'صفحه اصلی'), ('صفحه اخبار', 'صفحه اخبار'), ('صفحه تماس با ما', 'صفحه تماس با ما'), ('صفحه درباره ما', 'صفحه درباره ما')], max_length=500, unique=True)),
                ('حذف', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'نوع_عکس_ها',
            },
        ),
        migrations.CreateModel(
            name='پانویس',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('متن', models.CharField(max_length=500)),
                ('لینک', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'پانویس',
            },
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='social_network_contetnt_id',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_id',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='type',
        ),
        migrations.DeleteModel(
            name='Contact_us',
        ),
        migrations.RemoveField(
            model_name='content',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='logo_id',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logo_id',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='card',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='main_category',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Navigation_bar',
        ),
        migrations.RemoveField(
            model_name='new',
            name='card',
        ),
        migrations.RemoveField(
            model_name='new',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='new',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='new',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='news_category',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='news_category_new',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='news_category_new',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='other_program',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='post_category',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='post_category_post',
            name='post_category_id',
        ),
        migrations.RemoveField(
            model_name='post_category_post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='social_network_content',
            name='type',
        ),
        migrations.RemoveField(
            model_name='social_network_new',
            name='type',
        ),
        migrations.RemoveField(
            model_name='social_network_post',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user_type_permission',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='user_type_permission',
            name='user_type_id',
        ),
        migrations.RemoveField(
            model_name='value_proposition',
            name='media_id',
        ),
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Banner_type',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='Main_category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='News_category',
        ),
        migrations.DeleteModel(
            name='News_category_new',
        ),
        migrations.DeleteModel(
            name='Other_program',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post_category',
        ),
        migrations.DeleteModel(
            name='Post_category_post',
        ),
        migrations.DeleteModel(
            name='Social_network_content',
        ),
        migrations.DeleteModel(
            name='Social_network_new',
        ),
        migrations.DeleteModel(
            name='Social_network_post',
        ),
        migrations.DeleteModel(
            name='Social_network_type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_type',
        ),
        migrations.DeleteModel(
            name='User_type_permission',
        ),
        migrations.DeleteModel(
            name='Value_proposition',
        ),
        migrations.AddField(
            model_name='بنر',
            name='نوع',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.نوع_عکس'),
        ),
    ]
