# Generated by Django 2.0.5 on 2018-10-18 12:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0002_auto_20181018_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='خبر',
            old_name='شناسه_رسانه',
            new_name='شناسه_عکس',
        ),
        migrations.RenameField(
            model_name='خبر',
            old_name='عکس_مارکتینگ',
            new_name='شناسه_عکس_مارکتینگ',
        ),
        migrations.RenameField(
            model_name='سرویس',
            old_name='شناسه_رسانه',
            new_name='شناسه_عکس',
        ),
        migrations.RenameField(
            model_name='منوی_غذا',
            old_name='شناسه_رسانه',
            new_name='شناسه_عکس',
        ),
        migrations.RenameField(
            model_name='منوی_محبوب_رستوران',
            old_name='شناسه_رسانه',
            new_name='شناسه_عکس',
        ),
        migrations.AlterField(
            model_name='خبر',
            name='شرح_خبر',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='منوی_غذا',
            name='متن',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
