# Generated by Django 2.0.5 on 2018-10-18 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0003_auto_20181018_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='بنر',
            name='جایگزین',
            field=models.CharField(default=1, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='خبر',
            name='جایگزین',
            field=models.CharField(default=None, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='درباره_ما',
            name='جایگزین',
            field=models.CharField(default=0, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='سرویس',
            name='جایگزین',
            field=models.CharField(default=django.utils.timezone.now, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='لوگو',
            name='جایگزین',
            field=models.CharField(default=None, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='منوی_غذا',
            name='جایگزین',
            field=models.CharField(default=None, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='منوی_محبوب_رستوران',
            name='جایگزین',
            field=models.CharField(default=None, help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='بنر',
            name='شناسه_بنر',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='رسانه',
            name='جایگزین',
            field=models.CharField(help_text='یک جایگزین مناسب برای عکس وارد کنید تا در صورت نیاز بجای عکس نمایش داده شود.', max_length=500),
        ),
        migrations.AlterField(
            model_name='لوگو',
            name='شناسه_لوگو',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='منوی_غذا',
            name='شناسه_عکس',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='منوی_محبوب_رستوران',
            name='شناسه_عکس',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه'),
        ),
    ]
