# Generated by Django 2.0.5 on 2018-10-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0004_auto_20181018_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='تماس_با_ما',
            name='deleted',
        ),
        migrations.AddField(
            model_name='تماس_با_ما',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='بنر',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='تماس_با_ما',
            name='ایمیل',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='تماس_با_ما',
            name='تلفن',
            field=models.CharField(help_text='شماره های تماس را با الگوی روبرو وارد کنید: ۱۲۳۴۵۶ − ۱۲۳۴۵۶.', max_length=500),
        ),
        migrations.AlterField(
            model_name='تماس_با_ما',
            name='طول_جغرافیایی',
            field=models.FloatField(help_text='طول جغرافیایی رستوران را با دقت دو رقم اعشار وارد کنید.'),
        ),
        migrations.AlterField(
            model_name='تماس_با_ما',
            name='عرض_جغرافیایی',
            field=models.FloatField(help_text='عرض جغرافیایی ریتوران را با دقت دو رقم اعشار وارد کنید.'),
        ),
        migrations.AlterField(
            model_name='خبر',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='خبر',
            name='شناسه_عکس',
            field=models.ForeignKey(blank=True, default=None, help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nmedia', to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='خبر',
            name='شناسه_عکس_مارکتینگ',
            field=models.ForeignKey(blank=True, default=None, help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nmarketing', to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='درباره_ما',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='درباره_ما',
            name='عکس۱',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='ax1', to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='درباره_ما',
            name='عکس۲',
            field=models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='ax2', to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='رسانه',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='سربرگ',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='سرویس',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='سرویس',
            name='شناسه_عکس',
            field=models.ForeignKey(blank=True, default=None, help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmedia', to='mesineapp.رسانه'),
        ),
        migrations.AlterField(
            model_name='لوگو',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='منوی_غذا',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='منوی_غذا',
            name='محتویات',
            field=models.CharField(help_text='محتویات غذا را به صورت مختصر بنویسید.', max_length=500),
        ),
        migrations.AlterField(
            model_name='منوی_محبوب_رستوران',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='نوع_شبکه_اجتماعی',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='نوع_شبکه_اجتماعی',
            name='متن',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='نوع_عکس',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
        migrations.AlterField(
            model_name='پانویس',
            name='حذف',
            field=models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.'),
        ),
    ]
