# Generated by Django 2.0.5 on 2018-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0005_auto_20181020_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='نوع_عکس',
            name='نوع',
            field=models.CharField(choices=[('صفحه اصلی', 'صفحه اصلی'), ('صفحه اخبار', 'صفحه اخبار'), ('صفحه تماس با ما', 'صفحه تماس با ما'), ('صفحه درباره ما', 'صفحه درباره ما'), ('منوی غذا', 'منوی غذا')], max_length=500, unique=True),
        ),
    ]
