# Generated by Django 2.0.5 on 2018-10-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0006_auto_20181024_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='شبکه_اجتماعی',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('نام_کاربری', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.')),
                ('نوع_شبکه_اجتماعی', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesineapp.نوع_شبکه_اجتماعی')),
            ],
            options={
                'verbose_name_plural': 'شبکه_اجتماعی',
            },
        ),
        migrations.AlterField(
            model_name='منوی_محبوب_رستوران',
            name='توضیح',
            field=models.CharField(max_length=500),
        ),
    ]
