# Generated by Django 2.0.5 on 2018-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0007_auto_20181024_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='نوع_عکس',
            name='نوع',
            field=models.CharField(choices=[('صفحه اصلی', 'صفحه اصلی'), ('صفحه اخبار', 'صفحه اخبار'), ('صفحه تماس با ما', 'صفحه تماس با ما'), ('صفحه درباره ما', 'صفحه درباره ما'), ('صفحه منوی غذا', 'صفحه منوی غذا')], max_length=500, unique=True),
        ),
    ]
