# Generated by Django 2.0.5 on 2018-11-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0008_auto_20181024_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ارزش_های_پیشنهادی',
            fields=[
                ('شناسه', models.AutoField(primary_key=True, serialize=False)),
                ('ارزش_پیشنهادی', models.CharField(max_length=500)),
                ('حذف', models.IntegerField(default=0, help_text='در این قسمت هر عددی که جایگزین 0 شود به معنی حذف شدن این نمونه از سایت است.')),
                ('شناسه_عکس', models.ForeignKey(help_text='شناسه رسانه مورد نظر را انتخاب کرده یا رسانه ای جدید ایجاد کنید.', on_delete=django.db.models.deletion.CASCADE, to='mesineapp.رسانه')),
            ],
            options={
                'verbose_name_plural': 'ارزش_های_پیشنهادی',
            },
        ),
    ]
