# Generated by Django 2.0.5 on 2018-11-17 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0009_ارزش_های_پیشنهادی'),
    ]

    operations = [
        migrations.AddField(
            model_name='خبر',
            name='تاریخ',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 15, 19, 55, 676696), verbose_name='Date'),
        ),
    ]
