# Generated by Django 2.0.5 on 2018-11-17 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0010_خبر_تاریخ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='خبر',
            name='تاریخ',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 15, 21, 44, 828317), verbose_name='Date'),
        ),
    ]
