# Generated by Django 2.0.5 on 2018-11-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0011_auto_20181117_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='خبر',
            name='تاریخ',
        ),
    ]
