# Generated by Django 2.0.5 on 2018-11-17 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0012_remove_خبر_تاریخ'),
    ]

    operations = [
        migrations.AddField(
            model_name='خبر',
            name='تاریخ',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 15, 36, 26, 895425), verbose_name='Date'),
        ),
    ]
