# Generated by Django 2.0.5 on 2018-11-17 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesineapp', '0013_خبر_تاریخ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='خبر',
            name='تاریخ',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
